### ISSUE TITLE
Why do all of the output's remain the same?

### ISSUE THREAD

**Issue by ifacodes** [math-fehr/fast-wfc#2]
Using windows 10 with VS Code and Msys64  to compile.

for some reason all the output's remain the same.

and half of them consistently fail? I assume that is intended at the moment.

**Comment by math-fehr** [comment]
Thanks for spotting that, this was not intended.

It seems that random_device, which I used to generate the seeds for each instance, is not implemented non-deterministically on windows. I have thus changed the random number generator for non-linux target, by using the C rand function.

The commit e3d64aec03ea87a494dbf952f5927de2925bdd33 should fix that I hope (I can't test it on a windows machine right now).

**Comment by ifacodes** [comment]
Okay thanks! I'll test it out tonight

**Comment by ifacodes** [comment]
The results do vary but some patterns still fail. 

`Chess started!
Chess finished!
Chess finished!
Chess started!
failed!
failed!
failed!
failed!
failed!
failed!
failed!
failed!
failed!
failed!
Skyline started!
Skyline finished!
Skyline finished!
Flowers started!
Flowers finished!
Flowers finished!
Hogs started!
Hogs finished!
Hogs finished!
Hogs started!
Hogs finished!
failed!
failed!
Hogs finished!
Knot started!
Knot finished!
Knot finished!
Less Rooms started!
Less Rooms finished!
Less Rooms finished!
Mountains started!
failed!
Mountains finished!
Mountains finished!
Office started!
Office finished!
Office finished!
Paths started!
Paths finished!
Paths finished!
Platformer started!
Platformer finished!
Platformer finished!
Platformer started!
Platformer finished!
Platformer finished!
Red Maze started!
Red Maze finished!
Red Maze finished!
Rooms started!
Rooms finished!
Rooms finished!
Rooms finished!
Rule 126 started!
Rule 126 finished!
Rule 126 finished!
Simple Knot started!
Simple Knot finished!
Simple Knot finished!
Simple Maze started!
Simple Maze finished!
Simple Maze finished!
Simple Wall started!
Simple Wall finished!
failed!
Simple Wall finished!
Simple Wall started!
Simple Wall finished!
Simple Wall finished!
Simple Wall started!
Simple Wall finished!
Simple Wall finished!
Simple Wall started!
Simple Wall finished!
Simple Wall finished!
Trick Knot started!
Trick Knot finished!
Trick Knot finished!
Village started!
Village finished!
Village finished!
Water started!
Water finished!
Water finished!
Cat started!
failed!
failed!
failed!
Cat finished!
Cat finished!
Cats started!
failed!
failed!
failed!
failed!
failed!
failed!
failed!
Cats finished!
Cats finished!
Skyline 2 started!
Skyline 2 finished!
Skyline 2 finished!
Angular started!
Angular finished!
Angular finished!
City started!
City finished!
failed!
City finished!
Colored City started!
Colored City finished!
Colored City finished!
Dungeon started!
Dungeon finished!
Dungeon finished!
Lake started!
Lake finished!
Lake finished!
Link started!
failed!
failed!
failed!
Link finished!
Link finished!
Link 2 started!
Link 2 finished!
Link 2 finished!
Mazelike started!
Mazelike finished!
failed!
failed!
Mazelike finished!
Nested started!
Nested finished!
failed!
Nested finished!
Magic Office started!
Magic Office finished!
failed!
failed!
Magic Office finished!
Office 2 started!
Office 2 finished!
Office 2 finished!
Qud started!
Qud finished!
Qud finished!
Red Dot started!
Red Dot finished!
Red Dot finished!
Scaled Maze started!
Scaled Maze finished!
Scaled Maze finished!
Sewers started!
Sewers finished!
Sewers finished!
Skew 1 started!
failed!
failed!
Skew 1 finished!
failed!
Skew 1 finished!
Skew 2 started!
Skew 2 finished!
Skew 2 finished!
Smile City started!
failed!
failed!
Smile City finished!
Smile City finished!
Spirals started!
Spirals finished!
Spirals finished!
Town started!
Town finished!
Town finished!
3Bricks started!
3Bricks finished!
failed!
failed!
failed!
failed!
failed!
3Bricks finished!
Village started!
Village finished!
Village finished!
Summer tiles started!
Summer finished!
Castle tiles started!
failed!
Castle finished!
Circuit Turnless started!
Circuit finished!
Knots Standard started!
Knots finished!
Knots Dense started!
failed!
failed!
failed!
failed!
failed!
failed!
failed!
failed!
failed!
failed!
Knots Crossless started!
Knots finished!
Knots TE started!
failed!
failed!
failed!
failed!
failed!
failed!
failed!
failed!
Knots finished!
Knots T started!
Knots finished!
Knots CL started!
Knots finished!
Knots CE started!
failed!
failed!
Knots finished!
Knots C started!
Knots finished!
Knots Fabric started!
Knots finished!
Knots Dense Fabric started!
Knots finished!
Rooms tiles started!
Rooms finished!
Circles tiles started!
Circles finished!
Circles Large Circles started!
Circles finished!
Circles Large Circles and Solid started!
Circles finished!
Circles No Solid started!
Circles finished!
Summer tiles started!
Summer finished!
Knots Standard started!
Knots finished!
Summer tiles started!
Summer finished!
Circuit Turnless started!
Circuit finished!
All samples done in 7s, 524ms.`

This is the output of by terminal if it helps.

**Comment by math-fehr** [comment]
Yes, that is normal.
I should change the error message though. "failed!" means that the WFC algorithm had to restart on an instance. WFC does not guarantee to produce an output (simply because there is not always a solution, like some instances of Chess), and thus restart some number of times (it's 10 here, hardcoded in the main), or until it found a solution.
It's perfectly normal to have some examples that don't produce an output after 10 try though, since some solutions are harder to find than others. The problem is NP-hard after all.

**Comment by ifacodes** [comment]
AH, okay that actually makes a lot more sense now. 

for using rand() in windows, can you get away without having to use srand() anywhere? seeing as how if you don't use srand() it uses 1 as the seed (iirc).

**Comment by math-fehr** [comment]
Not really, srand() initialize the pseudo-random number generator that is used by rand().
